using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VPet.Plugin.AutoMTL
{
	internal class Constants
	{
		// This is not very clean but i really can't be arsed to do something better
		// Again from https://github.com/dmytrovoytko/SublimeText-Translate
		public static string googleLangJSON = """{"auto":"Automatic","af":"Afrikaans","sq":"Albanian","am":"Amharic","ar":"Arabic","hy":"Armenian","as":"Assamese","ay":"Aymara","az":"Azerbaijani","bm":"Bambara","eu":"Basque","be":"Belarusian","bn":"Bengali","bho":"Bhojpuri","bs":"Bosnian","bg":"Bulgarian","ca":"Catalan","ceb":"Cebuano","ny":"Chichewa (Nyanja)","zh-CN":"Chinese (Simplified)","zh-TW":"Chinese (Traditional)","co":"Corsican","hr":"Croatian","cs":"Czech","da":"Danish","dv":"Dhivehi","doi":"Dogri","nl":"Dutch","en":"English","eo":"Esperanto","et":"Estonian","ee":"Ewe","fil":"Filipino (Tagalog)","fi":"Finnish","fr":"French","fy":"Frisian","gl":"Galician","ka":"Georgian","de":"German","el":"Greek","gn":"Guarani","gu":"Gujarati","ht":"Haitian Creole","ha":"Hausa","haw":"Hawaiian","iw":"Hebrew","hi":"Hindi","hmn":"Hmong","hu":"Hungarian","is":"Icelandic","ig":"Igbo","ilo":"Ilocano","id":"Indonesian","ga":"Irish","it":"Italian","ja":"Japanese","jw":"Javanese","kn":"Kannada","kk":"Kazakh","km":"Khmer","rw":"Kinyarwanda","gom":"Konkani","ko":"Korean","kri":"Krio","ku":"Kurdish (Kurmanji)","ckb":"Kurdish (Sorani)","ky":"Kyrgyz","lo":"Lao","la":"Latin","lv":"Latvian","ln":"Lingala","lt":"Lithuanian","lg":"Luganda","lb":"Luxembourgish","mk":"Macedonian","mai":"Maithili","mg":"Malagasy","ms":"Malay","ml":"Malayalam","mt":"Maltese","mi":"Maori","mr":"Marathi","mni-Mtei":"Meiteilon (Manipuri)","lus":"Mizo","mn":"Mongolian","my":"Myanmar (Burmese)","ne":"Nepali","no":"Norwegian","or":"Odia (Oriya)","om":"Oromo","ps":"Pashto","fa":"Persian","pl":"Polish","pt":"Portuguese (Portugal, Brazil)","pa":"Punjabi","qu":"Quechua","ro":"Romanian","ru":"Russian","sm":"Samoan","sa":"Sanskrit","gd":"Scots Gaelic","nso":"Sepedi","sr":"Serbian","st":"Sesotho","sn":"Shona","sd":"Sindhi","si":"Sinhala (Sinhalese)","sk":"Slovak","sl":"Slovenian","so":"Somali","es":"Spanish","su":"Sundanese","sw":"Swahili","sv":"Swedish","tg":"Tajik","ta":"Tamil","tt":"Tatar","te":"Telugu","th":"Thai","ti":"Tigrinya","ts":"Tsonga","tr":"Turkish","tk":"Turkmen","ak":"Twi (Akan)","uk":"Ukrainian","ur":"Urdu","ug":"Uyghur","uz":"Uzbek","vi":"Vietnamese","cy":"Welsh","xh":"Xhosa","yi":"Yiddish","yo":"Yoruba","zu":"Zulu"}""";
		public static string bingLangJSON = """{"auto-detect":"Automatic","sq":"Albanian","am":"Amharic","ar":"Arabic","hy":"Armenian","as":"Assamese","az":"Azerbaijani","bn":"Bangla","ba":"Bashkir","eu":"Basque","bs":"Bosnian","bg":"Bulgarian","yue":"Cantonese (Traditional)","ca":"Catalan","lzh":"Chinese (Literary)","zh-Hans":"Chinese Simplified","zh-Hant":"Chinese Traditional","hr":"Croatian","cs":"Czech","da":"Danish","prs":"Dari","dv":"Divehi","nl":"Dutch","en":"English","et":"Estonian","fo":"Faroese","fj":"Fijian","fil":"Filipino","fi":"Finnish","fr":"French","fr-CA":"French (Canada)","gl":"Galician","ka":"Georgian","de":"German","el":"Greek","gu":"Gujarati","ht":"Haitian Creole","he":"Hebrew","hi":"Hindi","mww":"Hmong Daw","hu":"Hungarian","is":"Icelandic","id":"Indonesian","ikt":"Inuinnaqtun","iu":"Inuktitut","iu-Latn":"Inuktitut (Latin)","ga":"Irish","it":"Italian","ja":"Japanese","kn":"Kannada","kk":"Kazakh","km":"Khmer","tlh-Latn":"Klingon (Latin)","ko":"Korean","ku":"Kurdish (Central)","kmr":"Kurdish (Northern)","ky":"Kyrgyz","lo":"Lao","lv":"Latvian","lt":"Lithuanian","mk":"Macedonian","mg":"Malagasy","ms":"Malay","ml":"Malayalam","mt":"Maltese","mr":"Marathi","mn-Cyrl":"Mongolian (Cyrillic)","mn-Mong":"Mongolian (Traditional)","my":"Myanmar (Burmese)","mi":"Māori","ne":"Nepali","nb":"Norwegian","or":"Odia","ps":"Pashto","fa":"Persian","pl":"Polish","pt":"Portuguese (Brazil)","pt-PT":"Portuguese (Portugal)","pa":"Punjabi","otq":"Querétaro Otomi","ro":"Romanian","ru":"Russian","sm":"Samoan","sr-Cyrl":"Serbian (Cyrillic)","sr-Latn":"Serbian (Latin)","sk":"Slovak","sl":"Slovenian","so":"Somali","es":"Spanish","sw":"Swahili","sv":"Swedish","ty":"Tahitian","ta":"Tamil","tt":"Tatar","te":"Telugu","th":"Thai","bo":"Tibetan","ti":"Tigrinya","to":"Tongan","tr":"Turkish","tk":"Turkmen","uk":"Ukrainian","hsb":"Upper Sorbian","ur":"Urdu","ug":"Uyghur","uz":"Uzbek (Latin)","vi":"Vietnamese","cy":"Welsh","yua":"Yucatec Maya","zu":"Zulu"}""";
	}
}
